source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.3'

target 'ViroSample' do
    use_frameworks!
end

target 'ViroKit' do
    use_frameworks!
end

pod 'GVRKit', '1.100.0'
pod 'GVRAudioSDK', '1.100.0'
pod 'AWSDynamoDB', '2.6.7'
